name: Deploy to Shopify

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: modern-ecommerce-theme

      - name: Lint
        run: npm run lint --if-present
        working-directory: modern-ecommerce-theme

      - name: Type check
        run: npm run type-check --if-present
        working-directory: modern-ecommerce-theme

      - name: Build assets
        run: npm run build
        working-directory: modern-ecommerce-theme

      - name: Deploy to Shopify
        uses: pgrimaud/action-shopify@v1.3.0
        env:
          SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_PASSWORD }}
          SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_STORE_URL }}
          SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_THEME_ID }}
